apiVersion: v1
kind: ServiceAccount
metadata:
  name: k-charted-server
  labels:
    app: k-charted-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k-charted-server
  labels:
    app: k-charted-server
rules:
- apiGroups: ["monitoring.kiali.io"]
  resources:
  - monitoringdashboards
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k-charted-server
  labels:
    app: k-charted-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k-charted-server
subjects:
- kind: ServiceAccount
  name: k-charted-server
  namespace: VAR_NAMESPACE
